### ISSUE TITLE
XMPL Library 4.1.0, build 7 - Errors

### ISSUE THREAD

**Issue by wb77** [XMPieLab/XMPL-NG#12]
Errors when using the XMPL NG library from URL https://ajax.xmcircle.com/ajax/libs/XMPL-NG/4.1/xmpl.min.js (XMPL Library 4.1.0, build 7)
xmpProvider.api.getAdorValues errors as the RID is not being passed in the URL
Sample sites use an older version XMPL Library 4.1.0, build 2 - this version works correctly.

Regards,
Wayne

**Comment by vschi** [comment]
Correct. 

The transition from 
XMPL Library 4.0.0, build 2 to  XMPL Library 4.1.0, build 4
broke the possibility to provide the RID from one page to another. 
Specially visible for register or update when the success page should be opened.

Opened a bug just in case this issue was not seen.

**Comment by orenlevy** [comment]
Hi,
We are working on a fix for this issue, we will have a fix for it by the end of the week.

**Comment by morenoraf** [comment]
Hi,

This issue is fixed.

Please check and let us know it's OK on your end.

**Comment by vschi** [comment]
It is fixed.
